/* Replace with your SQL commands */
-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_name character varying COLLATE pg_catalog."default",
    user_type character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone_no character varying COLLATE pg_catalog."default",
    years_of_experience integer,
    company_size integer,
    "GST_number" character varying COLLATE pg_catalog."default",
    scocial_links character varying COLLATE pg_catalog."default",
    polices character varying COLLATE pg_catalog."default",
    terms character varying COLLATE pg_catalog."default",
    "isActive" boolean,
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

-- Table: public.job_categories

-- DROP TABLE IF EXISTS public.job_categories;

CREATE TABLE IF NOT EXISTS public.job_categories
(
    job_category_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category_name character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT job_categories_pkey PRIMARY KEY (job_category_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.job_categories
    OWNER to postgres;

-- Table: public.job_works

-- DROP TABLE IF EXISTS public.job_works;

CREATE TABLE IF NOT EXISTS public.job_works
(
    job_work_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_work_name character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT job_works_pkey PRIMARY KEY (job_work_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.job_works
    OWNER to postgres;

-- Table: public.material_types

-- DROP TABLE IF EXISTS public.material_types;

CREATE TABLE IF NOT EXISTS public.material_types
(
    material_type_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    material_name character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT material_types_pkey PRIMARY KEY (material_type_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.material_types
    OWNER to postgres;

-- Table: public.files

-- DROP TABLE IF EXISTS public.files;

CREATE TABLE IF NOT EXISTS public.files
(
    file_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    file_name character varying COLLATE pg_catalog."default",
    path text COLLATE pg_catalog."default",
    mine_type character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    "updated _at" time with time zone,
    CONSTRAINT files_pkey PRIMARY KEY (file_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.files
    OWNER to postgres;

-- Table: public.jobs

-- DROP TABLE IF EXISTS public.jobs;

CREATE TABLE IF NOT EXISTS public.jobs
(
    job_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_category_id bigint,
    job_work_id bigint,
    document_id json,
    user_id bigint,
    material_type_id bigint,
    quantity numeric,
    descriptions text COLLATE pg_catalog."default",
    total_budget numeric,
    job_type character varying COLLATE pg_catalog."default",
    job_deadline character varying COLLATE pg_catalog."default",
    weight numeric,
    max_transportation_cost numeric,
    is_material_provided_by_company boolean,
    status character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at character varying COLLATE pg_catalog."default",
    CONSTRAINT jobs_pkey PRIMARY KEY (job_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.jobs
    OWNER to postgres;

-- Table: public.bids

-- DROP TABLE IF EXISTS public.bids;

CREATE TABLE IF NOT EXISTS public.bids
(
    bid_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_id bigint,
    user_id bigint,
    bidding_amount numeric,
    bidding_breakdown text COLLATE pg_catalog."default",
    delivery_days character varying COLLATE pg_catalog."default",
    scope_of_transportation character varying COLLATE pg_catalog."default",
    status character varying COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT bids_pkey PRIMARY KEY (bid_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bids
    OWNER to postgres;

-- Table: public.ratings

-- DROP TABLE IF EXISTS public.ratings;

CREATE TABLE IF NOT EXISTS public.ratings
(
    rating_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint,
    job_id bigint,
    rating character varying COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    created_at time with time zone,
    updated_at time with time zone,
    CONSTRAINT ratings_pkey PRIMARY KEY (rating_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ratings
    OWNER to postgres;


ALTER TABLE jobs ALTER COLUMN job_category_id TYPE VARCHAR;

ALTER TABLE jobs ALTER COLUMN job_work_id TYPE VARCHAR;